/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Comment = {
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  description?: string;
  views?: number;
  image?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Update = {
  _id: string;
  _type: "update";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  version?: string;
  views?: number;
  desc?: Markdown;
  smallDesc?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Markdown = string;

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: number;
  name?: string;
  email?: string;
  password?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageUrl?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = Comment | Slug | Update | SanityImageCrop | SanityImageHotspot | Markdown | Author | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/lib/queries.ts
// Variable: AUTHOR_BY_GITHUB_ID_QUERY
// Query: *[_type == "author" && id == $id][0]{    _id,    id,    name,    email,    password,    imageUrl,   }
export type AUTHOR_BY_GITHUB_ID_QUERYResult = {
  _id: string;
  id: number | null;
  name: string | null;
  email: string | null;
  password: string | null;
  imageUrl: string | null;
} | null;
// Variable: CHECK_FOR_EXISTING_AUTHOR
// Query: *[_type == "author" && email == $email][0]
export type CHECK_FOR_EXISTING_AUTHORResult = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: number;
  name?: string;
  email?: string;
  password?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  imageUrl?: string;
} | null;
// Variable: AUTHOR_BY_ID_QUERY
// Query: *[_type == "author" && email == $email][0]{  _id,  id,  name,  email,  password,  "image": image.asset->url,  imageUrl}
export type AUTHOR_BY_ID_QUERYResult = {
  _id: string;
  id: number | null;
  name: string | null;
  email: string | null;
  password: string | null;
  image: string | null;
  imageUrl: string | null;
} | null;
// Variable: UPDATES_QUERY
// Query: *[_type == "update" && defined(slug.current)] | order(_createdAt desc){  _id,  title,  _updatedAt,  _createdAt,  _rev,  _type,  slug,  smallDesc,  desc,  version,  views,  "image": image.asset->url,}
export type UPDATES_QUERYResult = Array<{
  _id: string;
  title: string | null;
  _updatedAt: string;
  _createdAt: string;
  _rev: string;
  _type: "update";
  slug: Slug | null;
  smallDesc: string | null;
  desc: Markdown | null;
  version: string | null;
  views: number | null;
  image: string | null;
}>;
// Variable: UPDATES_BY_SLUG_QUERY
// Query: *[_type == "update" && defined(slug.current) && slug.current == $slug][0]{  _id,  title,  _updatedAt,  _createdAt,  _rev,  _type,  slug,  smallDesc,  desc,  version,  views,  "image": image.asset->url,}
export type UPDATES_BY_SLUG_QUERYResult = {
  _id: string;
  title: string | null;
  _updatedAt: string;
  _createdAt: string;
  _rev: string;
  _type: "update";
  slug: Slug | null;
  smallDesc: string | null;
  desc: Markdown | null;
  version: string | null;
  views: number | null;
  image: string | null;
} | null;
// Variable: UPDATE_VIEWS_QUERY
// Query: *[_type == "update" && defined(slug.current) && slug.current == $slug][0]{      _id, slug, views   }
export type UPDATE_VIEWS_QUERYResult = {
  _id: string;
  slug: Slug | null;
  views: number | null;
} | null;
// Variable: COMMENT_QUERY
// Query: *[_type == "comment" && defined(slug.current)] | order(_createdAt desc) {   _id,  title,  _updatedAt,  _createdAt,  _rev,  _type,  slug,  author -> {   _id, name, email, "image": image.asset->url, imageUrl, _createdAt, _updatedAt, _rev, _type  },  description,   }
export type COMMENT_QUERYResult = Array<{
  _id: string;
  title: string | null;
  _updatedAt: string;
  _createdAt: string;
  _rev: string;
  _type: "comment";
  slug: Slug | null;
  author: {
    _id: string;
    name: string | null;
    email: string | null;
    image: string | null;
    imageUrl: string | null;
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    _type: "author";
  } | null;
  description: string | null;
}>;
// Variable: CHECK_FOR_ID_QUERY
// Query: *[_type == "author" && id == $generatedId][0]{      id   }
export type CHECK_FOR_ID_QUERYResult = {
  id: number | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n   *[_type == \"author\" && id == $id][0]{\n    _id,\n    id,\n    name,\n    email,\n    password,\n    imageUrl,\n   } \n": AUTHOR_BY_GITHUB_ID_QUERYResult;
    "\n   *[_type == \"author\" && email == $email][0]\n": CHECK_FOR_EXISTING_AUTHORResult;
    "\n   *[_type == \"author\" && email == $email][0]{\n  _id,\n  id,\n  name,\n  email,\n  password,\n  \"image\": image.asset->url,\n  imageUrl\n}\n": AUTHOR_BY_ID_QUERYResult;
    "\n   *[_type == \"update\" && defined(slug.current)] | order(_createdAt desc){\n  _id,\n  title,\n  _updatedAt,\n  _createdAt,\n  _rev,\n  _type,\n  slug,\n  smallDesc,\n  desc,\n  version,\n  views,\n  \"image\": image.asset->url,\n}\n": UPDATES_QUERYResult;
    "\n   *[_type == \"update\" && defined(slug.current) && slug.current == $slug][0]{\n  _id,\n  title,\n  _updatedAt,\n  _createdAt,\n  _rev,\n  _type,\n  slug,\n  smallDesc,\n  desc,\n  version,\n  views,\n  \"image\": image.asset->url,\n}\n": UPDATES_BY_SLUG_QUERYResult;
    "\n   *[_type == \"update\" && defined(slug.current) && slug.current == $slug][0]{\n      _id, slug, views\n   }\n": UPDATE_VIEWS_QUERYResult;
    "\n   *[_type == \"comment\" && defined(slug.current)] | order(_createdAt desc) {\n   _id,\n  title,\n  _updatedAt,\n  _createdAt,\n  _rev,\n  _type,\n  slug,\n  author -> {\n   _id, name, email, \"image\": image.asset->url, imageUrl, _createdAt, _updatedAt, _rev, _type\n  },\n  description,\n   }\n": COMMENT_QUERYResult;
    "\n   *[_type == \"author\" && id == $generatedId][0]{\n      id\n   }\n": CHECK_FOR_ID_QUERYResult;
  }
}
