import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const cardinal = localFont({
  src:[
    {
      path: './fonts/Cardinal.ttf',
      weight: "400",
      style: "normal",
    },
  ],
  variable: '--cardinal',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cardinal.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
